[package]
name = "workshop7-tokio-state-channel"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.43.0", features = ["macros", "rt-multi-thread", "time", "tokio-macros", "sync"] }
