[package]
name = "workshop6-iot-zeromq"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.1"
tokio = { version = "1.43.0", features = ["macros", "net", "rt-multi-thread", "time", "tokio-macros"] }
zmq = "0.10.0"
